In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

C:\Users\jko04\AppData\Local\Temp\ipykernel_8036\3777615979.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

In [62]:
txns = pd.read_csv('transactions_HIFO_Universal.csv')
txns.drop(index=len(txns)-1, inplace=True)
txns.tail()

,Date,Type,Transaction ID,Received Quantity,Received Currency,Received Currency Balance,Received Cost Basis (USD),Received Wallet,Received Address,Received Tag,...,Sent Currency Balance,Sent Cost Basis (USD),Sent Wallet,Sent Address,Sent Tag,Sent Comment,Fee Amount,Fee Currency,Realized Return (USD),Disabled
395,03/07/2022 01:51:53,Buy,NaN,10.000000,ATOM,...,...,Coinbase Pro - ATOM,NaN,NaN,...,...,...,Coinbase Pro - USD,NaN,NaN,NaN,1.120000,USD,...,NaN
396,03/14/2022 03:19:31,Buy,NaN,500.000000,USDC,...,...,Coinbase Pro - USDC,NaN,NaN,...,...,...,Coinbase Pro - USD,NaN,NaN,NaN,NaN,NaN,...,NaN
397,03/14/2022 03:23:17,Transfer,0x693b4e6f0b524a1c4959d86a81f785ff9397bbbb1d4f...,496.485537,USDC,...,...,ETH Wallet ...50a3d5 - ETH,0xedc5dfee8d76c45bf367194a4c7bb808d350a3d5,NaN,...,...,...,Coinbase Pro - USDC,0xEdC5DfEE8d76c45BF367194A4c7Bb808d350a3d5,NaN,NaN,4.515373,USDC,...,NaN
398,03/14/2022 03:24:42,Send,e6b25c3f22bf7f7ccc093e6e1354171b1e9d26be747d69...,NaN,NaN,...,...,NaN,NaN,NaN,...,...,...,ETH Wallet ...50a3d5 - ETH,0xedc5dfee8d76c45bf367194a4c7bb808d350a3d5,NaN,NaN,0.001453,ETH,...,NaN
399,03/14/2022 03:25:57,Send,0xae6319252aa5007a911e19cd619ebd745350991e767c...,NaN,NaN,...,...,NaN,NaN,NaN,...,...,...,ETH Wallet ...50a3d5 - ETH,0xedc5dfee8d76c45bf367194a4c7bb808d350a3d5,NaN,NaN,0.005348,ETH,...,NaN

In [63]:
tokens = dft.geckoFullList()
tokens.reset_index(inplace=True)
tokens = tokens[['symbol', 'id', 'name']]
tokens.symbol = tokens.symbol.str.upper()
tokens.rename(columns={'id':'nameid'}, inplace=True)

In [64]:
mapping = dict(tokens[['symbol', 'nameid']].values)
txns['received_id'] = txns['Received Currency'].map(mapping)
txns['sent_id'] = txns['Sent Currency'].map(mapping)
txns['Date'] = pd.to_datetime(txns['Date'])
txns['day'] = txns['Date'].apply(lambda x: x.strftime('%d-%m-%Y'))

In [65]:
txns.head()

,Date,Type,Transaction ID,Received Quantity,Received Currency,Received Currency Balance,Received Cost Basis (USD),Received Wallet,Received Address,Received Tag,...,Sent Address,Sent Tag,Sent Comment,Fee Amount,Fee Currency,Realized Return (USD),Disabled,received_id,sent_id,day
0,2017-12-12 18:27:37,Buy,NaN,0.563387,LTC,...,...,Coinbase - LTC Wallet,NaN,NaN,...,NaN,NaN,Bought Litecoin Using Visa debit ********6305,5.85,USD,...,NaN,litecoin,NaN,12-12-2017
1,2017-12-13 04:22:41,Buy,NaN,0.307622,LTC,...,...,Coinbase - LTC Wallet,NaN,NaN,...,NaN,NaN,Bought Litecoin Using Visa debit ********6305,3.41,USD,...,NaN,litecoin,NaN,13-12-2017
2,2017-12-13 18:35:49,Buy,NaN,0.017821,BTC,...,...,Coinbase - BTC Wallet,NaN,NaN,...,NaN,NaN,Bought Bitcoin Using Visa debit ********6305,9.26,USD,...,NaN,bitcoin,NaN,13-12-2017
3,2017-12-15 06:34:23,Buy,NaN,0.141976,ETH,...,...,Coinbase - ETH Wallet,NaN,NaN,...,NaN,NaN,Bought Ethereum Using Visa debit ********6305,3.41,USD,...,NaN,ethereum,NaN,15-12-2017
4,2017-12-21 16:13:38,Buy,NaN,0.005993,BTC,...,...,Coinbase - BTC Wallet,NaN,NaN,...,NaN,NaN,Bought Bitcoin Using Visa debit ********6305,3.41,USD,...,NaN,bitcoin,NaN,21-12-2017

In [77]:
# txns['Received Cost Basis (USD)'][0] = 1
txns.loc[txns.index == 0, 'Received Cost Basis (USD)'] = 0
txns.head()

,Date,Type,Transaction ID,Received Quantity,Received Currency,Received Currency Balance,Received Cost Basis (USD),Received Wallet,Received Address,Received Tag,...,Sent Address,Sent Tag,Sent Comment,Fee Amount,Fee Currency,Realized Return (USD),Disabled,received_id,sent_id,day
0,2017-12-12 18:27:37,Buy,NaN,0.563387,LTC,...,0,Coinbase - LTC Wallet,NaN,NaN,...,NaN,NaN,Bought Litecoin Using Visa debit ********6305,5.85,USD,...,NaN,litecoin,NaN,12-12-2017
1,2017-12-13 04:22:41,Buy,NaN,0.307622,LTC,...,...,Coinbase - LTC Wallet,NaN,NaN,...,NaN,NaN,Bought Litecoin Using Visa debit ********6305,3.41,USD,...,NaN,litecoin,NaN,13-12-2017
2,2017-12-13 18:35:49,Buy,NaN,0.017821,BTC,...,...,Coinbase - BTC Wallet,NaN,NaN,...,NaN,NaN,Bought Bitcoin Using Visa debit ********6305,9.26,USD,...,NaN,bitcoin,NaN,13-12-2017
3,2017-12-15 06:34:23,Buy,NaN,0.141976,ETH,...,...,Coinbase - ETH Wallet,NaN,NaN,...,NaN,NaN,Bought Ethereum Using Visa debit ********6305,3.41,USD,...,NaN,ethereum,NaN,15-12-2017
4,2017-12-21 16:13:38,Buy,NaN,0.005993,BTC,...,...,Coinbase - BTC Wallet,NaN,NaN,...,NaN,NaN,Bought Bitcoin Using Visa debit ********6305,3.41,USD,...,NaN,bitcoin,NaN,21-12-2017

In [78]:
from random import randint
from time import sleep

for i, row in txns.iterrows():
    txns.loc[txns.index == i, 'Received Cost Basis (USD)'] = dft.geckoPriceAt(row['received_id'], 'usd', row['day'])
    txns.loc[txns.index == i, 'Sent Cost Basis (USD)'] = dft.geckoPriceAt(row['sent_id'], 'usd', row['day'])

    sleep(randint(3,5))

nan 12-12-2017 'market_data'
nan 13-12-2017 'market_data'
nan 13-12-2017 'market_data'
nan 15-12-2017 'market_data'
nan 21-12-2017 'market_data'
nan 31-12-2017 'market_data'
nan 31-12-2017 'market_data'
nan 05-01-2018 'market_data'
nan 05-01-2018 'market_data'
nan 10-01-2018 'market_data'
nan 04-05-2018 'market_data'
nan 30-05-2018 'market_data'
nan 12-07-2018 'market_data'
nan 26-07-2018 'market_data'
nan 02-09-2018 'market_data'
nan 02-09-2018 'market_data'
nan 05-09-2018 'market_data'
nan 05-09-2018 'market_data'
nan 14-09-2018 'market_data'
nan 14-09-2018 'market_data'
nan 14-09-2018 'market_data'
nan 14-09-2018 'market_data'
nan 21-09-2018 'market_data'
nan 21-09-2018 'market_data'
nan 24-09-2018 'market_data'
nan 02-10-2018 'market_data'
nan 02-10-2018 'market_data'
nan 02-10-2018 'market_data'
nan 02-10-2018 'market_data'
nan 09-10-2018 'market_data'
nan 09-10-2018 'market_data'
nan 14-10-2018 'market_data'
nan 18-10-2018 'market_data'
nan 25-10-2018 'market_data'
nan 25-10-2018 'market_data'
nan 08-11-2018 'market_data'
nan 08-11-2018 'market_data'
nan 30-04-2019 'market_data'
nan 30-04-2019 'market_data'
nan 30-04-2019 'market_data'
nan 30-04-2019 'market_data'
nan 30-04-2019 'market_data'
nan 30-04-2019 'market_data'
nan 30-04-2019 'market_data'
nan 30-04-2019 'market_data'
nan 30-04-2019 'market_data'
nan 12-02-2020 'market_data'
nan 12-02-2020 'market_data'
nan 12-02-2020 'market_data'
nan 12-02-2020 'market_data'
nan 18-02-2020 'market_data'
nan 12-03-2020 'market_data'
nan 12-03-2020 'market_data'
nan 12-03-2020 'market_data'
nan 12-03-2020 'market_data'
nan 18-03-2020 'market_data'
nan 18-03-2020 'market_data'
nan 20-03-2020 'market_data'
nan 20-03-2020 'market_data'
nan 20-03-2020 'market_data'
nan 20-03-2020 'market_data'
nan 24-03-2020 'market_data'
nan 25-03-2020 'market_data'
nan 25-03-2020 'market_data'
nan 25-03-2020 'market_data'
nan 25-03-2020 'market_data'
nan 31-03-2020 'market_data'
nan 31-03-2020 'market_data'
nan 31-03-2020 'market_data'
nan 31-03-2020 'market_data'
nan 24-04-2020 'market_data'
nan 09-07-2020 'market_data'
nan 09-07-2020 'market_data'
nan 09-07-2020 'market_data'
nan 11-07-2020 'market_data'
nan 11-07-2020 'market_data'
nan 14-07-2020 'market_data'
nan 21-07-2020 'market_data'
nan 21-07-2020 'market_data'
nan 21-07-2020 'market_data'
nan 28-07-2020 'market_data'
nan 28-07-2020 'market_data'
nan 28-07-2020 'market_data'
nan 28-07-2020 'market_data'
nan 16-12-2020 'market_data'
nan 16-12-2020 'market_data'
nan 16-12-2020 'market_data'
nan 16-12-2020 'market_data'
nan 16-12-2020 'market_data'
nan 21-12-2020 'market_data'
nan 21-12-2020 'market_data'
nan 21-12-2020 'market_data'
nan 21-12-2020 'market_data'
nan 21-12-2020 'market_data'
nan 21-12-2020 'market_data'
nan 21-12-2020 'market_data'
nan 21-12-2020 'market_data'
nan 26-12-2020 'market_data'
nan 03-01-2021 'market_data'
nan 08-04-2021 'market_data'
nan 20-04-2021 'market_data'
nan 23-04-2021 'market_data'
nan 23-04-2021 'market_data'
nan 23-04-2021 'market_data'
nan 23-04-2021 'market_data'
nan 04-05-2021 'market_data'
nan 04-05-2021 'market_data'
nan 04-05-2021 'market_data'
nan 04-05-2021 'market_data'
nan 10-05-2021 'market_data'
nan 11-05-2021 'market_data'
nan 12-05-2021 'market_data'
nan 13-05-2021 'market_data'
nan 17-05-2021 'market_data'
nan 17-05-2021 'market_data'
nan 17-05-2021 'market_data'
nan 17-05-2021 'market_data'
nan 17-05-2021 'market_data'
nan 18-05-2021 'market_data'
nan 19-05-2021 'market_data'
nan 19-05-2021 'market_data'
nan 19-05-2021 'market_data'
nan 19-05-2021 'market_data'
nan 19-05-2021 'market_data'
nan 20-05-2021 'market_data'
nan 02-06-2021 'market_data'
nan 04-06-2021 'market_data'
nan 12-06-2021 'market_data'
nan 12-06-2021 'market_data'
nan 12-06-2021 'market_data'
nan 12-07-2021 'market_data'
nan 12-07-2021 'market_data'
nan 12-07-2021 'market_data'
nan 12-07-2021 'market_data'
nan 12-07-2021 'market_data'
nan 12-07-2021 'market_data'
nan 13-07-2021 'market_data'
nan 28-07-2021 'market_data'
nan 28-07-2021 'market_data'
nan 29-07-2021 'market_data'
nan 12-08-2021 'market_data'
nan 13-08-2021 'market_data'
nan 13-08-2021 'market_data'
nan 13-08-2021 'market_data'
nan 13-08-2021 'market_data'
nan 17-08-2021 'market_data'
nan 17-08-2021 'market_data'
nan 18-08-2021 'market_data'
nan 26-08-2021 'market_data'
nan 09-09-2021 'market_data'
nan 09-09-2021 'market_data'
nan 23-09-2021 'market_data'
nan 23-09-2021 'market_data'
nan 23-09-2021 'market_data'
nan 23-09-2021 'market_data'
nan 24-09-2021 'market_data'
nan 24-09-2021 'market_data'
nan 01-10-2021 'market_data'
nan 01-10-2021 'market_data'
nan 01-10-2021 'market_data'
nan 01-10-2021 'market_data'
nan 01-10-2021 'market_data'
nan 01-10-2021 'market_data'
nan 03-10-2021 'market_data'
nan 03-10-2021 'market_data'
nan 03-10-2021 'market_data'
nan 03-10-2021 'market_data'
nan 03-10-2021 'market_data'
nan 04-10-2021 'market_data'
nan 04-10-2021 'market_data'
nan 04-10-2021 'market_data'
nan 06-10-2021 'market_data'
nan 11-10-2021 'market_data'
nan 11-10-2021 'market_data'
nan 12-10-2021 'market_data'
nan 12-10-2021 'market_data'
nan 13-10-2021 'market_data'
nan 16-10-2021 'market_data'
nan 17-10-2021 'market_data'
nan 19-10-2021 'market_data'
nan 19-10-2021 'market_data'
nan 20-10-2021 'market_data'
nan 20-10-2021 'market_data'
nan 20-10-2021 'market_data'
nan 25-10-2021 'market_data'
nan 25-10-2021 'market_data'
nan 25-10-2021 'market_data'
nan 26-10-2021 'market_data'
nan 26-10-2021 'market_data'
nan 26-10-2021 'market_data'
nan 26-10-2021 'market_data'
nan 26-10-2021 'market_data'
nan 26-10-2021 'market_data'
nan 26-10-2021 'market_data'
nan 26-10-2021 'market_data'
nan 26-10-2021 'market_data'
nan 27-10-2021 'market_data'
nan 27-10-2021 'market_data'
nan 27-10-2021 'market_data'
nan 28-10-2021 'market_data'
nan 28-10-2021 'market_data'
nan 28-10-2021 'market_data'
nan 30-10-2021 'market_data'
nan 30-10-2021 'market_data'
nan 30-10-2021 'market_data'
nan 30-10-2021 'market_data'
nan 02-11-2021 'market_data'
nan 02-11-2021 'market_data'
nan 02-11-2021 'market_data'
nan 02-11-2021 'market_data'
nan 02-11-2021 'market_data'
nan 02-11-2021 'market_data'
nan 02-11-2021 'market_data'
nan 03-11-2021 'market_data'
nan 10-11-2021 'market_data'
nan 10-11-2021 'market_data'
nan 10-11-2021 'market_data'
nan 12-11-2021 'market_data'
nan 16-11-2021 'market_data'
nan 16-11-2021 'market_data'
nan 16-11-2021 'market_data'
nan 16-11-2021 'market_data'
nan 18-11-2021 'market_data'
nan 18-11-2021 'market_data'
nan 18-11-2021 'market_data'
nan 19-11-2021 'market_data'
nan 23-11-2021 'market_data'
nan 23-11-2021 'market_data'
nan 24-11-2021 'market_data'
nan 24-11-2021 'market_data'
nan 26-11-2021 'market_data'
nan 26-11-2021 'market_data'
nan 26-11-2021 'market_data'
nan 26-11-2021 'market_data'
nan 26-11-2021 'market_data'
nan 28-11-2021 'market_data'
nan 30-11-2021 'market_data'
nan 01-12-2021 'market_data'
nan 02-12-2021 'market_data'
nan 02-12-2021 'market_data'
nan 03-12-2021 'market_data'
nan 04-12-2021 'market_data'
nan 04-12-2021 'market_data'
nan 04-12-2021 'market_data'
nan 04-12-2021 'market_data'
nan 04-12-2021 'market_data'
nan 04-12-2021 'market_data'
nan 04-12-2021 'market_data'
nan 04-12-2021 'market_data'
nan 04-12-2021 'market_data'
nan 06-12-2021 'market_data'
nan 06-12-2021 'market_data'
nan 06-12-2021 'market_data'
nan 10-12-2021 'market_data'
nan 10-12-2021 'market_data'
nan 12-12-2021 'market_data'
nan 12-12-2021 'market_data'
nan 13-12-2021 'market_data'
nan 15-12-2021 'market_data'
nan 20-12-2021 'market_data'
nan 20-12-2021 'market_data'
nan 20-12-2021 'market_data'
nan 26-12-2021 'market_data'
nan 27-12-2021 'market_data'
nan 28-12-2021 'market_data'
nan 28-12-2021 'market_data'
nan 28-12-2021 'market_data'
nan 31-12-2021 'market_data'
nan 03-01-2022 'market_data'
nan 05-01-2022 'market_data'
nan 06-01-2022 'market_data'
nan 06-01-2022 'market_data'
nan 06-01-2022 'market_data'
nan 07-01-2022 'market_data'
nan 07-01-2022 'market_data'
nan 07-01-2022 'market_data'
nan 08-01-2022 'market_data'
nan 10-01-2022 'market_data'
nan 10-01-2022 'market_data'
nan 10-01-2022 'market_data'
nan 10-01-2022 'market_data'
nan 10-01-2022 'market_data'
nan 16-01-2022 'market_data'

nan 18-01-2022 'market_data'
nan 18-01-2022 'market_data'
nan 20-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 21-01-2022 'market_data'
nan 22-01-2022 'market_data'
nan 22-01-2022 'market_data'
nan 22-01-2022 'market_data'
nan 22-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 24-01-2022 'market_data'
nan 28-01-2022 'market_data'
nan 28-01-2022 'market_data'
nan 28-01-2022 'market_data'
nan 31-01-2022 'market_data'
nan 05-02-2022 'market_data'
nan 05-02-2022 'market_data'
nan 05-02-2022 'market_data'
nan 06-02-2022 'market_data'
nan 10-02-2022 'market_data'
nan 10-02-2022 'market_data'
nan 10-02-2022 'market_data'
nan 11-02-2022 'market_data'
nan 11-02-2022 'market_data'
nan 11-02-2022 'market_data'
nan 11-02-2022 'market_data'
nan 11-02-2022 'market_data'
nan 11-02-2022 'market_data'
nan 11-02-2022 'market_data'
nan 11-02-2022 'market_data'
nan 12-02-2022 'market_data'
nan 14-02-2022 'market_data'
nan 14-02-2022 'market_data'
nan 14-02-2022 'market_data'
nan 16-02-2022 'market_data'
nan 16-02-2022 'market_data'
nan 16-02-2022 'market_data'
nan 16-02-2022 'market_data'
nan 16-02-2022 'market_data'
nan 16-02-2022 'market_data'
nan 16-02-2022 'market_data'
nan 16-02-2022 'market_data'
nan 17-02-2022 'market_data'
nan 17-02-2022 'market_data'
nan 20-02-2022 'market_data'
nan 20-02-2022 'market_data'
nan 20-02-2022 'market_data'
nan 20-02-2022 'market_data'
nan 20-02-2022 'market_data'
nan 24-02-2022 'market_data'
nan 24-02-2022 'market_data'
nan 25-02-2022 'market_data'
nan 03-03-2022 'market_data'
nan 03-03-2022 'market_data'
nan 07-03-2022 'market_data'
nan 14-03-2022 'market_data'
nan 14-03-2022 'market_data'
nan 14-03-2022 'market_data'

In [2]:
txns = pd.read_csv('updated-txns.csv')

In [3]:
txns['Received Wallet'] = txns['Received Wallet'].str.split(' - ', 1).str[0]
txns['Sent Wallet'] = txns['Sent Wallet'].str.split(' - ', 1).str[0]
txns

,Unnamed: 0,Date,Type,Transaction ID,Received Quantity,Received Currency,Received Currency Balance,Received Cost Basis (USD),Received Wallet,Received Address,...,Sent Comment,Fee Amount,Fee Currency,Realized Return (USD),Disabled,received_id,sent_id,day,received_wallet,sent_wallet
0,0,2017-12-12 18:27:37,Buy,NaN,0.563387,LTC,...,320.907411,Coinbase,NaN,...,Bought Litecoin Using Visa debit ********6305,5.850000,USD,...,NaN,litecoin,NaN,12-12-2017,cb,cb
1,1,2017-12-13 04:22:41,Buy,NaN,0.307622,LTC,...,305.277042,Coinbase,NaN,...,Bought Litecoin Using Visa debit ********6305,3.410000,USD,...,NaN,litecoin,NaN,13-12-2017,cb,cb
2,2,2017-12-13 18:35:49,Buy,NaN,0.017821,BTC,...,16525.044489,Coinbase,NaN,...,Bought Bitcoin Using Visa debit ********6305,9.260000,USD,...,NaN,bitcoin,NaN,13-12-2017,cb,cb
3,3,2017-12-15 06:34:23,Buy,NaN,0.141976,ETH,...,693.097064,Coinbase,NaN,...,Bought Ethereum Using Visa debit ********6305,3.410000,USD,...,NaN,ethereum,NaN,15-12-2017,cb,cb
4,4,2017-12-21 16:13:38,Buy,NaN,0.005993,BTC,...,16355.238226,Coinbase,NaN,...,Bought Bitcoin Using Visa debit ********6305,3.410000,USD,...,NaN,bitcoin,NaN,21-12-2017,cb,cb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,2022-03-07 01:51:53,Buy,NaN,10.000000,ATOM,...,28.166506,Coinbase Pro,NaN,...,NaN,1.120000,USD,...,NaN,cosmos,NaN,07-03-2022,cbpro,cbpro
396,396,2022-03-14 03:19:31,Buy,NaN,500.000000,USDC,...,1.001094,Coinbase Pro,NaN,...,NaN,NaN,NaN,...,NaN,usd-coin,NaN,14-03-2022,cbpro,cbpro
397,397,2022-03-14 03:23:17,Transfer,0x693b4e6f0b524a1c4959d86a81f785ff9397bbbb1d4f...,496.485537,USDC,...,1.001094,ETH Wallet ...50a3d5,0xedc5dfee8d76c45bf367194a4c7bb808d350a3d5,...,NaN,4.515373,USDC,...,NaN,usd-coin,usd-coin,14-03-2022,metamask,cbpro
398,398,2022-03-14 03:24:42,Send,e6b25c3f22bf7f7ccc093e6e1354171b1e9d26be747d69...,NaN,NaN,...,1.000000,NaN,NaN,...,NaN,0.001453,ETH,...,NaN,NaN,ethereum,14-03-2022,NaN,metamask
399,399,2022-03-14 03:25:57,Send,0xae6319252aa5007a911e19cd619ebd745350991e767c...,NaN,NaN,...,1.000000,NaN,NaN,...,NaN,0.005348,ETH,...,NaN,NaN,usd-coin,14-03-2022,NaN,metamask

In [4]:
wallets = list(set(list(txns['Received Wallet'].values) + list(txns['Sent Wallet'].values)))
wallets

[nan,
 'Binance',
 'ETH Wallet ...C8859C',
 'ETH Wallet ...50a3d5',
 'Coinbase',
 'Coinbase Pro']

In [5]:
wallets.remove(wallets[0])
wallets

['Binance',
 'ETH Wallet ...C8859C',
 'ETH Wallet ...50a3d5',
 'Coinbase',
 'Coinbase Pro']

In [6]:
names = ['cbpro', 'ledger', 'binance', 'cb', 'metamask']
wallets = list(zip(wallets, names))
wallets

[('Binance', 'cbpro'),
 ('ETH Wallet ...C8859C', 'ledger'),
 ('ETH Wallet ...50a3d5', 'binance'),
 ('Coinbase', 'cb'),
 ('Coinbase Pro', 'metamask')]

In [7]:
wmapping = {w[0]:w[1] for w in list(wallets)}
wmapping

{'Binance': 'cbpro',
 'ETH Wallet ...C8859C': 'ledger',
 'ETH Wallet ...50a3d5': 'binance',
 'Coinbase': 'cb',
 'Coinbase Pro': 'metamask'}

In [39]:
txns.to_csv('updated-txns.csv')

In [3]:
tokens = dft.geckoFullList(names=True)
end = int(10000/250)
for i in range(2, end):
    temp = dft.geckoFullList(page=i, names=True)
    pd.concat([tokens, temp])
tokens.symbol = tokens.symbol.str.upper()
tokens.rename(columns={'id':'nameid'}, inplace=True)
tokens.to_csv('tokens_db.csv')

In [1]:
import pandas as pd
import numpy as np
from main import Wallet, Coin, Transaction
import defi_tools as dft

In [2]:
tokens = pd.read_csv('tokens_db.csv')
mapping = dict(tokens[['symbol', 'nameid']].values)
mapping['USD'] = 'usd'

In [3]:
test = pd.read_csv('test-txns.csv')

In [4]:
test['received_id'] = test['Received Currency'].map(mapping)
test['sent_id'] = test['Sent Currency'].map(mapping)
test['fee_id'] = test['Fee Currency'].map(mapping)

In [5]:
cbpro = Wallet('Coinbase Pro')
cb = Wallet('Coinbase')
binance = Wallet('Binance')
ledger = Wallet('Ledger')
metamask = Wallet('Metamask')
tempw = Wallet('tempw')

wallets = {'Coinbase Pro':cbpro, 'Coinbase':cb, 'Binance': binance}

In [6]:
for i, r in test.iterrows():
    print(i)
    t = pd.to_datetime(r['Date']).strftime('%d-%m-%Y')
    tp = r['Type']
    if tp == 'Buy' or tp == 'Trade' or tp == 'Sell':
        w = wallets[r['Received Wallet']]
        b = (r['received_id'],r['Received Quantity'])
        s = (r['sent_id'],r['Sent Quantity'])
        if r['Fee Amount']:
            f = (r['fee_id'], r['Fee Amount'])
        else:
            f = (0, 0)
        Transaction.transact(t, w, b, s, f, tp)
    elif tp == 'Send':
        w = wallets[r['Sent Wallet']]
        tk = r['sent_id']
        amt = r['Sent Quantity']
        if r['Fee Amount']:
            f = (r['fee_id'], r['Fee Amount'])
        else:
            f = (0, 0)
        Transaction.send(t, w, tk, amt, f)
    elif tp == 'Receive':
        w = wallets[r['Received Wallet']]
        tk = r['received_id']
        amt = r['Received Quantity']
        Transaction.receive(t, w, tk, amt)
    elif tp == 'Transfer':
        o = wallets[r['Sent Wallet']]
        d = wallets[r['Received Wallet']]
        tk = r['sent_id']
        a = r['Sent Quantity']
        if r['Fee Amount']:
            f = (r['fee_id'], r['Fee Amount'])
        else:
            f = (0, 0)
        Transaction.transfer(t, o, d, tk, a, f)
    else:
        print(f'{tp} not supported.')

0
usd 5.85
Sent 200.0 USD from Coinbase
Received 0.56338723 LTC at Coinbase
Bought 0.56338723 LTC with 200.0 USD.
LTC Balance: 0.56338723
USD Balance: -200.0
1
usd 3.41
Sent 100.0 USD from Coinbase
Received 0.30762244 LTC at Coinbase
Bought 0.30762244 LTC with 100.0 USD.
LTC Balance: 0.8710096700000001
USD Balance: -300.0
2
usd 9.26
Sent 300.0 USD from Coinbase
Received 0.01782139 BTC at Coinbase
Bought 0.01782139 BTC with 300.0 USD.
BTC Balance: 0.01782139
USD Balance: -600.0
3
usd 3.41
Sent 100.0 USD from Coinbase
Received 0.14197607 ETH at Coinbase
Bought 0.14197607 ETH with 100.0 USD.
ETH Balance: 0.14197607
USD Balance: -700.0
4
usd 3.41
Sent 100.0 USD from Coinbase
Received 0.00599276 BTC at Coinbase
Bought 0.00599276 BTC with 100.0 USD.
BTC Balance: 0.02381415
USD Balance: -800.0
5
bitcoin 0.00114174
Sent 0.00894174 BTC from Coinbase
6
Received 0.0078 BTC at Binance
7
iota 0.025
Sent 0.0065375 BTC from Binance
Received 25.0 MIOTA at Binance
MIOTA Balance: 25.0
BTC Balance: 0.0012624999999999997
8
bitcoin 0.00108737
Sent 0.01487241 BTC from Coinbase
9
Received 0.01378504 BTC at Binance
10
stellar 0.1
Sent 0.004 BTC from Binance
Received 100.0 XLM at Binance
XLM Balance: 100.0
BTC Balance: 0.01104754
11
power-ledger 0.052
Sent 0.005512 BTC from Binance
Received 52.0 POWR at Binance
POWR Balance: 52.0
BTC Balance: 0.005535539999999999
12
qtum 0.00153
Sent 0.005508 BTC from Binance
Received 1.53 QTUM at Binance
QTUM Balance: 1.53
BTC Balance: 2.753999999999951e-05
13
usd 6.0
Sent 206.0 USD from Coinbase
Received 0.01396827 BTC at Coinbase
Bought 0.01396827 BTC with 206.0 USD.
BTC Balance: 0.013968269999999998
USD Balance: -1006.0
14
usd 3.41
Sent 100.0 USD from Coinbase
Received 0.00995665 BTC at Coinbase
Bought 0.00995665 BTC with 100.0 USD.
BTC Balance: 0.023924919999999995
USD Balance: -1106.0
15
usd 1.0
Sent 100.0 USD from Coinbase
Received 0.17440936 ETH at Coinbase
Bought 0.17440936 ETH with 100.0 USD.
ETH Balance: 0.31638543
USD Balance: -1206.0
16
usd 1.0
Sent 100.0 USD from Coinbase
Received 0.22115383 ETH at Coinbase
Bought 0.22115383 ETH with 100.0 USD.
ETH Balance: 0.53753926
USD Balance: -1306.0
17
usd 2.99
Sent 100.0 USD from Coinbase
Received 0.20298474 ETH at Coinbase
Bought 0.20298474 ETH with 100.0 USD.
ETH Balance: 0.740524
USD Balance: -1406.0
18
usd 2.99
Sent 100.0 USD from Coinbase
Received 0.013259 BTC at Coinbase
Bought 0.013259 BTC with 100.0 USD.
BTC Balance: 0.037183919999999995
USD Balance: -1506.0
19
usd 2.99
Sent 0.0147995 BTC from Coinbase
Received 100.0 USD at Coinbase
Sold 0.0147995 BTC and made 100.0 USD.
USD Balance: -1406.0
BTC Balance: 0.022384419999999995
20
usd 2.99
Sent 0.40150325 ETH from Coinbase
Received 100.0 USD at Coinbase
Sold 0.40150325 ETH and made 100.0 USD.
USD Balance: -1306.0
ETH Balance: 0.33902075
21
nan nan
Sent 200.0 USD from Coinbase Pro
Received 200.0 USD at Coinbase Pro
USD Balance: 0.0
USD Balance: 0.0
22
nan nan
Sent 0.85106382 ETH from Coinbase
Received 0.85106382 ETH at Coinbase
ETH Balance: 0.33902075
ETH Balance: 0.33902075
23
usd 1.0
Sent 0.5 LTC from Coinbase
Received 16.0 USD at Coinbase
Sold 0.5 LTC and made 16.0 USD.
USD Balance: -1290.0
LTC Balance: 0.37100967000000007

In [9]:
cb.transactions

{'date': ['12-12-2017',
  '12-12-2017',
  '13-12-2017',
  '13-12-2017',
  '13-12-2017',
  '13-12-2017',
  '15-12-2017',
  '15-12-2017',
  '21-12-2017',
  '21-12-2017',
  '31-12-2017',
  '05-01-2018',
  '10-01-2018',
  '10-01-2018',
  '04-05-2018',
  '04-05-2018',
  '30-05-2018',
  '30-05-2018',
  '12-07-2018',
  '12-07-2018',
  '26-07-2018',
  '26-07-2018',
  '02-09-2018',
  '02-09-2018',
  '05-09-2018',
  '05-09-2018',
  '05-09-2018',
  '05-09-2018',
  '24-09-2018',
  '24-09-2018',
  '01-01-2020',
  '01-01-2020'],
 'token': ['usd',
  'litecoin',
  'usd',
  'litecoin',
  'usd',
  'bitcoin',
  'usd',
  'ethereum',
  'usd',
  'bitcoin',
  'bitcoin',
  'bitcoin',
  'usd',
  'bitcoin',
  'usd',
  'bitcoin',
  'usd',
  'ethereum',
  'usd',
  'ethereum',
  'usd',
  'ethereum',
  'usd',
  'bitcoin',
  'bitcoin',
  'usd',
  'ethereum',
  'usd',
  'ethereum',
  'ethereum',
  'litecoin',
  'usd'],
 'amount': [200.0,
  0.56338723,
  100.0,
  0.30762244,
  300.0,
  0.01782139,
  100.0,
  0.14197607,
  100.0,
  0.00599276,
  0.00894174,
  0.01487241,
  206.0,
  0.01396827,
  100.0,
  0.00995665,
  100.0,
  0.17440936,
  100.0,
  0.22115383,
  100.0,
  0.20298474,
  100.0,
  0.013259,
  0.0147995,
  100.0,
  0.40150325,
  100.0,
  0.85106382,
  0.85106382,
  0.5,
  16.0],
 'basis': [1,
  320.907411291884,
  1,
  305.277042325734,
  1,
  16525.0444892988,
  1,
  693.09706413276,
  1,
  16355.2382257401,
  14856.533739801744,
  18356.862000110046,
  1,
  15509.2701268168,
  1,
  9551.13518381566,
  1,
  561.7406614509548,
  1,
  443.0254304264658,
  1,
  468.73749232171497,
  1,
  7211.270767868822,
  29364.25734176288,
  1,
  1139.0881690220149,
  1,
  nan,
  244.7847954629194,
  82.6606237435916,
  1],
 'cost': [200.0,
  180.79513753420525,
  100.0,
  93.91006863622556,
  300.0,
  294.4992626111448,
  100.0,
  98.40319729410723,
  100.0,
  98.01301742968624,
  132.84326200253486,
  273.0107779790567,
  206.0,
  216.63767263431131,
  100.0,
  95.09731012793819,
  100.0,
  97.97282924963771,
  100.0,
  97.97677072621144,
  100.0,
  95.1465580071753,
  100.0,
  95.61423911117271,
  434.57632652941976,
  100.0,
  457.3476018988883,
  100.0,
  nan,
  208.32748310459084,
  41.3303118717958,
  16.0],
 'type': ['sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'send',
  'send',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy',
  'sell',
  'buy'],
 'profit': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}